language: rust
rust: stable
os: linux

branches:
  only:
  - authoring

cache:
  directories:
  - $HOME/.cargo
  - $HOME/gutenberg

install_broken:
# Download gutenberg.
- test -d $HOME/gutenberg/.git || git clone https://github.com/Keats/gutenberg.git $HOME/gutenberg
- cd $HOME/gutenberg; git fetch --all --tags
# Switch to the latest tagged version.
- cd $HOME/gutenberg; git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
# Clone submodules.
- cd $HOME/gutenberg; git submodule update --init
# Clone and update the OftLisp syntax.
- cd $HOME/gutenberg/sublime_syntaxes; test -d Sublime-OftLisp/.git || git clone https://github.com/oftlisp/Sublime-OftLisp.git
- cd $HOME/gutenberg/sublime_syntaxes/Sublime-OftLisp; git pull
# Update the lockfile. (Yes, I know this defeats the purpose of the lockfile.)
- cd $HOME/gutenberg; cargo update
# Create new packdump files.
- cd $HOME/gutenberg/components/rendering; cargo run --example generate_sublime synpack ../../sublime_syntaxes ../../sublime_syntaxes/newlines.packdump ../../sublime_syntaxes/nonewlines.packdump
# Install gutenberg.
- cd $HOME/gutenberg; cargo install --force
- cd $TRAVIS_BUILD_DIR

install:
- cd ~/.cargo/bin
- curl -L https://github.com/Keats/gutenberg/releases/download/v0.3.4/gutenberg-v0.3.4-x86_64-unknown-linux-gnu.tar.gz | tar xz
- cd $TRAVIS_BUILD_DIR

script:
- gutenberg build --base-url https://remexre.xyz/

deploy:
  fqdn: remexre.xyz
  github_token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: authoring
  provider: pages
  skip-cleanup: true
  target-branch: master
