base_url = "https://remexre.xyz/"
title = "remexre.xyz"
highlight_code = true
highlight_theme = "monokai"

generate_rss = true
compile_sass = false

[external_renderers]
dot = "set -e; echo -n '<p class=\"graphviz\">'; dot -Tsvg | tail -n +4; echo '</p>'"

[[taxonomies]]
name = "tags"
rss = true
