baseURL = "https://remexre.xyz/"
canonifyURLs = true
relativeURLs = true
preserveTaxonomyNames = true
PygmentsCodeFences = true
PygmentsStyle = "colorful"
pygmentsUseClasses = true
title = "remexre.xyz"

[taxonomies]
tag = "tags"
