base_url = "https://remexre.xyz/"

title = "remexre.xyz"
description = "remexre.xyz"
language_code = "en"

highlight_code = true
highlight_theme = "demain"

generate_rss = true
rss_limit = 100

taxonomies = [
	{name = "tags"}
]

compile_sass = false
extra_syntaxes = [
	"syntaxes/Sublime-OftLisp"
]
