base_url = "https://remexre.xyz/"
title = "remexre.xyz"
highlight_code = true
highlight_theme = "monokai"

# allow_external = true

generate_rss = true
compile_sass = false

[[taxonomies]]
name = "categories"
rss = true

[[taxonomies]]
name = "tags"
rss = true
