baseURL = "https://remexre.xyz/"
enableRobotsTXT = true
preserveTaxonomyNames = true
PygmentsCodeFences = true
PygmentsStyle = "colorful"
pygmentsUseClasses = true
title = "remexre.xyz"

[taxonomies]
tag = "tags"
