name: Build
on:
  push:
    branches:
    - fib
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build
      run: |
        nix build
        mkdir public
        cp -r result/* public/
        chown -R $(id -u):$(id -g) public
        find public -type d -exec chmod 755 {} \;
        find public -type f -exec chmod 644 {} \;
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: master
        folder: result
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
